language: node_js
node_js:
  - "lts/*"

dist: trusty
sudo: false

cache:
  bundler: true
  yarn: true
  directories:
    - node_modules

before_script:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.27.1/hugo_0.27.1_Linux-64bit.tar.gz
  - tar -xf hugo*.tar.gz
  - export PATH=$PATH:$PWD/hugo_0.27.1_Linux-64bit/
  - yarn global add gulp

script:
  - ./deploy.sh

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master
