language: node_js
node_js:
  - "lts/*"

dist: trusty

cache:
  bundler: true
  yarn: true
  directories:
    - node_modules

install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.27.1/hugo_0.27.1_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb
  - yarn global add gulp

script:
  - ./deploy.sh

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master
