baseURL: '/'
title: HymnsRepo
theme: lanyon
languageCode: en-US
canonifyurls: true
pluralizelisttitles: false
footnoteReturnLinkContents: "↩"

params:
  siteurl:      https://hymnsrepo.com/
  tagline:      A catholic hymn repository
  description:  A repository of hymns and songs used in catholic settings.



disableKinds:
  - taxonomy
  - taxonomyTerm
  - RSS

sitemap:
  changefreq: monthly
  priority: 0.5